class TrainKey():
	A = 'algorithm'
	A_SERIALIZE = 'serialize_function'
	A_DSERIALIZE = 'deserialize_function'
	A_ID = 'id'
	A_PARAM = 'param'
	A_FILE = 'save_file'
	A_FEATURES = 'features'
	A_LABELS = 'labels'
	M = 'model'
	P = 'preprocessing'
	P_UT = 'unit_transformation'
	D = 'data'
	D_FILE = 'file'
	D_T = 'type'
	D_HT = 'header_type'
	D_S = 'schema'
	D_C = 'constants'
	S_N = 'names'
	S_U = 'units'

class InterfaceKey():
	M = 'models'
	M_ID = 'id'
	M_F = 'model'
	M_DIC = 'translation'
	M_UPDATE = 'update'