/* Generated By:JJTree: Do not edit this line. ASTCONSTANTS.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package pilots.compiler.trainer_parser;

public
class ASTCONSTANTS extends SimpleNode {
  public ASTCONSTANTS(int id) {
    super(id);
  }

  public ASTCONSTANTS(PilotsParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PilotsParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=cb1248e2b17c0d77ff34e0c791cd5dfe (do not edit this line) */
