/* Generated By:JJTree: Do not edit this line. ASTNUMBERASSIGNMENT.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package pilots.compiler.trainer_parser;

public
class ASTNUMBERASSIGNMENT extends SimpleNode {
  public ASTNUMBERASSIGNMENT(int id) {
    super(id);
  }

  public ASTNUMBERASSIGNMENT(PilotsParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PilotsParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b82cf6ddd887d6816909ca2414f36916 (do not edit this line) */
