/* Generated By:JJTree: Do not edit this line. ASTPROGRAM.java Version 6.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package pilots.compiler.trainer_parser;

public
class ASTPROGRAM extends SimpleNode {
  public ASTPROGRAM(int id) {
    super(id);
  }

  public ASTPROGRAM(PilotsParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PilotsParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=da78f2674abd8d96ec3507e3638590e8 (do not edit this line) */
