/* Generated By:JavaCC: Do not edit this line. PilotsParserTreeConstants.java Version 6.0_1 */
package pilots.compiler.trainer_parser;

public interface PilotsParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCONSTANTS = 1;
  public int JJTDATA = 2;
  public int JJTDATAITEM = 3;
  public int JJTFILE = 4;
  public int JJTMODELUSER = 5;
  public int JJTSTRING = 6;
  public int JJTMODEL = 7;
  public int JJTSCHEMA = 8;
  public int JJTPREPROCESS = 9;
  public int JJTFEATURES = 10;
  public int JJTLABELS = 11;
  public int JJTALGORITHM = 12;
  public int JJTTRAINING = 13;
  public int JJTMAP = 14;
  public int JJTMAPITEM = 15;
  public int JJTPREDICATE = 16;
  public int JJTFUNCEXP = 17;
  public int JJTNUMMAP = 18;
  public int JJTNUMMAPITEM = 19;
  public int JJTEQUATION = 20;
  public int JJTVARS = 21;
  public int JJTVAR = 22;
  public int JJTEXPS = 23;
  public int JJTEXP = 24;
  public int JJTEXP2 = 25;
  public int JJTFUNC = 26;
  public int JJTNUMBER = 27;
  public int JJTVALUE = 28;


  public String[] jjtNodeName = {
    "PROGRAM",
    "CONSTANTS",
    "Data",
    "DataItem",
    "File",
    "ModelUser",
    "String",
    "Model",
    "Schema",
    "Preprocess",
    "Features",
    "Labels",
    "Algorithm",
    "Training",
    "Map",
    "MapItem",
    "Predicate",
    "FuncExp",
    "NumMap",
    "NumMapItem",
    "EQUATION",
    "VARS",
    "VAR",
    "Exps",
    "Exp",
    "Exp2",
    "Func",
    "Number",
    "Value",
  };
}
/* JavaCC - OriginalChecksum=b57b3bd8e45a6a9e0819d5150b037c4e (do not edit this line) */
