/* Generated By:JavaCC: Do not edit this line. PilotsParserDefaultVisitor.java Version 6.0_1 */
package pilots.compiler.trainer_parser;

public class PilotsParserDefaultVisitor implements PilotsParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPROGRAM node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTCONSTANTS node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNUMBERASSIGNMENT node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTReal node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTData node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTDataItem node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFile node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTModelUser node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTString node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTModel node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTSchema node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPreprocess node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFeatures node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLabels node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAlgorithm node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTraining node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMap node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMapItem node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTPredicate node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFuncExp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNumMap node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNumMapItem node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTVARS node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTVAR node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExps node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExp2 node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFunc node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNumber node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTValue node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=22d575aa18a481f2ea1122379e1c5a54 (do not edit this line) */
