/* Generated By:JavaCC: Do not edit this line. PilotsParserTreeConstants.java Version 6.0_1 */
package pilots.compiler.trainer_parser;

public interface PilotsParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTCONSTANTS = 1;
  public int JJTNUMBERASSIGNMENT = 2;
  public int JJTREAL = 3;
  public int JJTDATA = 4;
  public int JJTDATAITEM = 5;
  public int JJTFILE = 6;
  public int JJTMODELUSER = 7;
  public int JJTSTRING = 8;
  public int JJTMODEL = 9;
  public int JJTSCHEMA = 10;
  public int JJTPREPROCESS = 11;
  public int JJTFEATURES = 12;
  public int JJTLABELS = 13;
  public int JJTALGORITHM = 14;
  public int JJTTRAINING = 15;
  public int JJTMAP = 16;
  public int JJTMAPITEM = 17;
  public int JJTPREDICATE = 18;
  public int JJTFUNCEXP = 19;
  public int JJTNUMMAP = 20;
  public int JJTNUMMAPITEM = 21;
  public int JJTVARS = 22;
  public int JJTVAR = 23;
  public int JJTEXPS = 24;
  public int JJTEXP = 25;
  public int JJTEXP2 = 26;
  public int JJTFUNC = 27;
  public int JJTNUMBER = 28;
  public int JJTVALUE = 29;


  public String[] jjtNodeName = {
    "PROGRAM",
    "CONSTANTS",
    "NUMBERASSIGNMENT",
    "Real",
    "Data",
    "DataItem",
    "File",
    "ModelUser",
    "String",
    "Model",
    "Schema",
    "Preprocess",
    "Features",
    "Labels",
    "Algorithm",
    "Training",
    "Map",
    "MapItem",
    "Predicate",
    "FuncExp",
    "NumMap",
    "NumMapItem",
    "VARS",
    "VAR",
    "Exps",
    "Exp",
    "Exp2",
    "Func",
    "Number",
    "Value",
  };
}
/* JavaCC - OriginalChecksum=8872fb76c2ee20ac1a8bc2a09acf8e47 (do not edit this line) */
