/* Generated By:JavaCC: Do not edit this line. TrainerParserDefaultVisitor.java Version 7.0.4 */
package pilots.compiler.trainer.parser;

public class TrainerParserDefaultVisitor implements TrainerParserVisitor{
  public Object defaultVisit(SimpleNode node, Object data){
    node.childrenAccept(this, data);
    return data;
  }
  public Object visit(SimpleNode node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTTrainer node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTConstant node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTData node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFile node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTModelUser node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFeature node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTLabel node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTAlgorithm node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMap node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTMapItem node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTVars node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExps node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExp node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTExp2 node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTFunc node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTNumber node, Object data){
    return defaultVisit(node, data);
  }
  public Object visit(ASTValue node, Object data){
    return defaultVisit(node, data);
  }
}
/* JavaCC - OriginalChecksum=ecf294742ce00ae5a5bca28db4f3d6b7 (do not edit this line) */
