/* Generated By:JavaCC: Do not edit this line. TrainerParserTreeConstants.java Version 7.0.4 */
package pilots.compiler.trainer.parser;

public interface TrainerParserTreeConstants
{
  public int JJTTRAINER = 0;
  public int JJTCONSTANT = 1;
  public int JJTDATA = 2;
  public int JJTFILE = 3;
  public int JJTMODELUSER = 4;
  public int JJTSEQUENCE = 5;
  public int JJTFEATURE = 6;
  public int JJTLABEL = 7;
  public int JJTTEST_FEATURE = 8;
  public int JJTTEST_LABEL = 9;
  public int JJTALGORITHM = 10;
  public int JJTMAP = 11;
  public int JJTMAPITEM = 12;
  public int JJTVARS = 13;
  public int JJTEXPS = 14;
  public int JJTEXPS2 = 15;
  public int JJTEXP = 16;
  public int JJTEXP2 = 17;
  public int JJTFUNC = 18;
  public int JJTNUMBER = 19;
  public int JJTVALUE = 20;


  public String[] jjtNodeName = {
    "Trainer",
    "Constant",
    "Data",
    "File",
    "ModelUser",
    "Sequence",
    "Feature",
    "Label",
    "Test_Feature",
    "Test_Label",
    "Algorithm",
    "Map",
    "MapItem",
    "Vars",
    "Exps",
    "Exps2",
    "Exp",
    "Exp2",
    "Func",
    "Number",
    "Value",
  };
}
/* JavaCC - OriginalChecksum=88082d84f58fabeeba6f9bac01ada63a (do not edit this line) */
