/* Generated By:JavaCC: Do not edit this line. TrainerParserTreeConstants.java Version 7.0.4 */
package pilots.compiler.trainer.parser;

public interface TrainerParserTreeConstants
{
  public int JJTTRAINER = 0;
  public int JJTCONSTANT = 1;
  public int JJTDATA = 2;
  public int JJTFILE = 3;
  public int JJTMODELUSER = 4;
  public int JJTFEATURE = 5;
  public int JJTLABEL = 6;
  public int JJTALGORITHM = 7;
  public int JJTMAP = 8;
  public int JJTMAPITEM = 9;
  public int JJTVARS = 10;
  public int JJTEXPS = 11;
  public int JJTEXP = 12;
  public int JJTEXP2 = 13;
  public int JJTFUNC = 14;
  public int JJTNUMBER = 15;
  public int JJTVALUE = 16;


  public String[] jjtNodeName = {
    "Trainer",
    "Constant",
    "Data",
    "File",
    "ModelUser",
    "Feature",
    "Label",
    "Algorithm",
    "Map",
    "MapItem",
    "Vars",
    "Exps",
    "Exp",
    "Exp2",
    "Func",
    "Number",
    "Value",
  };
}
/* JavaCC - OriginalChecksum=0b2cba337941f7b7f6e60625a2813065 (do not edit this line) */
