/* Generated By:JavaCC: Do not edit this line. TrainerParserVisitor.java Version 7.0.4 */
package pilots.compiler.trainer.parser;

public interface TrainerParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTTrainer node, Object data);
  public Object visit(ASTConstant node, Object data);
  public Object visit(ASTData node, Object data);
  public Object visit(ASTFile node, Object data);
  public Object visit(ASTModelUser node, Object data);
  public Object visit(ASTSequence node, Object data);
  public Object visit(ASTFeature node, Object data);
  public Object visit(ASTLabel node, Object data);
  public Object visit(ASTTest_Feature node, Object data);
  public Object visit(ASTTest_Label node, Object data);
  public Object visit(ASTAlgorithm node, Object data);
  public Object visit(ASTMap node, Object data);
  public Object visit(ASTMapItem node, Object data);
  public Object visit(ASTVars node, Object data);
  public Object visit(ASTExps node, Object data);
  public Object visit(ASTExps2 node, Object data);
  public Object visit(ASTExp node, Object data);
  public Object visit(ASTExp2 node, Object data);
  public Object visit(ASTFunc node, Object data);
  public Object visit(ASTNumber node, Object data);
  public Object visit(ASTValue node, Object data);
}
/* JavaCC - OriginalChecksum=50a7e4be214ac89f7837723c2e3a49c5 (do not edit this line) */
