/* Generated By:JJTree: Do not edit this line. ASTConstInSignature.java Version 7.0 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package pilots.compiler.parser;

public
class ASTConstInSignature extends SimpleNode {
  public ASTConstInSignature(int id) {
    super(id);
  }

  public ASTConstInSignature(PilotsParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(PilotsParserVisitor visitor, Object data) {

    return
    visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=6bc9ff4e918188ccae0927ab0a75820e (do not edit this line) */
