/* Generated By:JavaCC: Do not edit this line. PilotsParserTreeConstants.java Version 5.0 */
package pilots.compiler.parser;

public interface PilotsParserTreeConstants
{
  public int JJTPILOTS = 0;
  public int JJTINPUT = 1;
  public int JJTOUTPUT = 2;
  public int JJTERROR = 3;
  public int JJTSIGNATURE = 4;
  public int JJTESTIMATE = 5;
  public int JJTCORRECT = 6;
  public int JJTVARS = 7;
  public int JJTCONST = 8;
  public int JJTDIM = 9;
  public int JJTMETHOD = 10;
  public int JJTMETHODS = 11;
  public int JJTTIME = 12;
  public int JJTEXPS = 13;
  public int JJTEXP = 14;
  public int JJTEXP2 = 15;
  public int JJTFUNC = 16;
  public int JJTNUMBER = 17;
  public int JJTVALUE = 18;


  public String[] jjtNodeName = {
    "Pilots",
    "Input",
    "Output",
    "Error",
    "Signature",
    "Estimate",
    "Correct",
    "Vars",
    "Const",
    "Dim",
    "Method",
    "Methods",
    "Time",
    "Exps",
    "Exp",
    "Exp2",
    "Func",
    "Number",
    "Value",
  };
}
/* JavaCC - OriginalChecksum=ee7a9b25e5e521448b3172c9f461e94e (do not edit this line) */
