/* Generated By:JavaCC: Do not edit this line. PilotsParserTreeConstants.java Version 5.0 */
package pilots.compiler.parser;

public interface PilotsParserTreeConstants
{
  public int JJTPILOTS = 0;
  public int JJTINPUT = 1;
  public int JJTOUTPUT = 2;
  public int JJTERROR = 3;
  public int JJTVARS = 4;
  public int JJTDIMS = 5;
  public int JJTMETHOD = 6;
  public int JJTMETHODS = 7;
  public int JJTTIME = 8;
  public int JJTEXPS = 9;
  public int JJTEXP = 10;
  public int JJTEXP2 = 11;
  public int JJTFUNC = 12;
  public int JJTNUMBER = 13;
  public int JJTVALUE = 14;


  public String[] jjtNodeName = {
    "Pilots",
    "Input",
    "Output",
    "Error",
    "Vars",
    "Dims",
    "Method",
    "Methods",
    "Time",
    "Exps",
    "Exp",
    "Exp2",
    "Func",
    "Number",
    "Value",
  };
}
/* JavaCC - OriginalChecksum=5d0454ee8305064ead4a7b5074da7870 (do not edit this line) */
