/* Generated By:JavaCC: Do not edit this line. PilotsParserTreeConstants.java Version 5.0 */
package pilots.compiler.parser;

public interface PilotsParserTreeConstants
{
  public int JJTPILOTS = 0;
  public int JJTINPUT = 1;
  public int JJTOUTPUT = 2;
  public int JJTERROR = 3;
  public int JJTSIGNATURE = 4;
  public int JJTCORRECT = 5;
  public int JJTVARS = 6;
  public int JJTCONST = 7;
  public int JJTDIMS = 8;
  public int JJTMETHOD = 9;
  public int JJTMETHODS = 10;
  public int JJTTIME = 11;
  public int JJTEXPS = 12;
  public int JJTEXP = 13;
  public int JJTEXP2 = 14;
  public int JJTFUNC = 15;
  public int JJTNUMBER = 16;
  public int JJTVALUE = 17;


  public String[] jjtNodeName = {
    "Pilots",
    "Input",
    "Output",
    "Error",
    "Signature",
    "Correct",
    "Vars",
    "Const",
    "Dims",
    "Method",
    "Methods",
    "Time",
    "Exps",
    "Exp",
    "Exp2",
    "Func",
    "Number",
    "Value",
  };
}
/* JavaCC - OriginalChecksum=79cbce03ca67e485991aefdfc95dc3c7 (do not edit this line) */
