/* Generated By:JJTree&JavaCC: Do not edit this line. PilotsParserConstants.java */
package pilots.compiler.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface PilotsParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PROGRAM_START = 6;
  /** RegularExpression Id. */
  int INPUTS = 7;
  /** RegularExpression Id. */
  int OUTPUTS = 8;
  /** RegularExpression Id. */
  int ERRORS = 9;
  /** RegularExpression Id. */
  int USING = 10;
  /** RegularExpression Id. */
  int AT = 11;
  /** RegularExpression Id. */
  int EVERY = 12;
  /** RegularExpression Id. */
  int CLOSEST = 13;
  /** RegularExpression Id. */
  int EUCLIDEAN = 14;
  /** RegularExpression Id. */
  int INTERPOLATE = 15;
  /** RegularExpression Id. */
  int NSEC = 16;
  /** RegularExpression Id. */
  int USEC = 17;
  /** RegularExpression Id. */
  int MSEC = 18;
  /** RegularExpression Id. */
  int SEC = 19;
  /** RegularExpression Id. */
  int MIN = 20;
  /** RegularExpression Id. */
  int HOUR = 21;
  /** RegularExpression Id. */
  int DAY = 22;
  /** RegularExpression Id. */
  int SQRT = 23;
  /** RegularExpression Id. */
  int SIN = 24;
  /** RegularExpression Id. */
  int COS = 25;
  /** RegularExpression Id. */
  int TAN = 26;
  /** RegularExpression Id. */
  int ARCSIN = 27;
  /** RegularExpression Id. */
  int ARCCOS = 28;
  /** RegularExpression Id. */
  int ARCTAN = 29;
  /** RegularExpression Id. */
  int ABS = 30;
  /** RegularExpression Id. */
  int PROGRAM_END = 31;
  /** RegularExpression Id. */
  int DIGIT = 32;
  /** RegularExpression Id. */
  int LPAR = 33;
  /** RegularExpression Id. */
  int RPAR = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int INTEGER = 36;
  /** RegularExpression Id. */
  int SCALEFACTOR = 37;
  /** RegularExpression Id. */
  int REAL = 38;
  /** RegularExpression Id. */
  int LETTER = 39;
  /** RegularExpression Id. */
  int VAR = 40;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"program\"",
    "\"inputs\"",
    "\"outputs\"",
    "\"errors\"",
    "\"using\"",
    "\"at\"",
    "\"every\"",
    "\"closest\"",
    "\"euclidean\"",
    "\"interpolate\"",
    "\"nsec\"",
    "\"usec\"",
    "\"msec\"",
    "\"sec\"",
    "\"min\"",
    "\"hour\"",
    "\"day\"",
    "\"sqrt\"",
    "\"sin\"",
    "\"cos\"",
    "\"tan\"",
    "\"asin\"",
    "\"acos\"",
    "\"atan\"",
    "\"abs\"",
    "\"end\"",
    "<DIGIT>",
    "\"(\"",
    "\")\"",
    "\",\"",
    "<INTEGER>",
    "<SCALEFACTOR>",
    "<REAL>",
    "<LETTER>",
    "<VAR>",
    "\";\"",
    "\":\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\"^\"",
  };

}
